create database NEW ;
CREATE TABLE TEMP 
(ID INT,
NAME VARCHAR(1000),
NO INT,
PRIMARY KEY(ID,NO)
);
DROP TABLE TEMP;
INSERT INTO TEMP 
VALUES 
(01 , "A" ,12),
(02,"VB",1531),
(105,"SHOPIA",25),
(106,"CALEB FOSTER",52);
SELECT * FROM TEMP;
CREATE TABLE NEW1(
	ID INT,
	NAME VARCHAR (20),
	CITY VARCHAR (30),
    FOREIGN KEY (ID ) REFERENCES TEMP (ID) 
    );
INSERT INTO NEW1 
VALUES 
(111,"ASD","ZIR"),
(121,"AFD","DSGF")
;
select *from temp where no = 12;
select * from NEW1 where id >100 and city="zir";


use NEW;
select * 
FROM NEW1 WHERE NAME NOT IN ("ASD");
SELECT * FROM NEW1 
ORDER BY CITY ASC 
LIMIT 1;
  
SELECT CITY ,AVG(ID) 
FROM NEW1
GROUP BY CITY
ORDER BY AVG(MARKS);





CREATE DATABASE DATA;

CREATE TABLE STUDENT (
ID INT PRIMARY KEY,
NAME VARCHAR (50));

INSERT INTO STUDENT 
VALUES 
(101,"ASHVIN"),
(102,"CHOUHAN");

CREATE TABLE FULL_NAME(
ID INT  PRIMARY KEY,
NAME VARCHAR(1000),
MODE VARCHAR(1000),
CITY VARCHAR(1000));

DROP TABLE FULL_NAME;


INSERT INTO FULL_NAME 
VALUES 
(101 , "OLIVIA", "NETBANKING", "PORTLAND"),
(102,  "ETHAN","CREDIT CARD","MIAMI"),
(103,	"MAYA","CREDIT CARD","SEATTLE"),
(104,   "LIAM DONOVAN","NETBANKING","DENVER"),
(105,"SHOPIA","CREDIT CARD","NEW ORLEANS"),
(106,"CALEB FOSTER","DEBIT CARD","MINNEAPOLIS"),
(107,"AVA PATEL","DEBIT CARD","PHONIX"),
(108,"LUCAS CARTEN","NET BANKING","BOSTON"),
(109,"ISABELLA MARTINEZ","NETBANKING","NASHVILE"),
(110,"JACKSON BROOK","CREDIT CARD","BOSTON");

SELECT CITY ,COUNT(ID)
FROM INFO
GROUP BY CITY;

UPDATE INFO
SET NAME ="ASHVIN"
WHERE NAME ="AVA PATEL";

SET SQL_SAFE_UPDATES=0;

UPDATE INFO
SET MODE="CREDIT CARD"
WHERE MODE="NETBANKING";

DELETE FROM INFO 
WHERE CITY="BOSTON";
  
ALTER TABLE INFO 
ADD COLUMN STATUS CHAR;

ALTER TABLE INFO
DROP COLUMN STATUS;

ALTER TABLE INFO
RENAME TO DETAIL;

ALTER TABLE DETAIL
ADD COLUMN AGE INT NULL DEFAULT 20;

ALTER TABLE DETAIL
MODIFY COLUMN AGE VARCHAR (2);

INSERT INTO DETAIL
(ID , NAME , AGE )
VALUES 
(1,"KALU",20),
(2,"RAMU",200);

ALTER TABLE DETAIL
CHANGE AGE STU_AGE INT;

ALTER TABLE DETAIL
DROP COLUMN STU_AGE;

ALTER TABLE DETAIL
RENAME TO INFO;


truncate table DETAIL;

ALTER TABLE info
RENAME TO FULL_NAME;

DELETE FROM FULL_NAME
WHERE ID=101;

ALTER TABLE FULL_NAME
DROP COLUMN ID;


SELECT * 
FROM TEMP AS T
INNER JOIN FULL_NAME AS F
ON T.ID=F.ID;


SELECT *
FROM TEMP AS T
LEFT JOIN FULL_NAME AS F
ON T.ID=F.ID;

SELECT *
FROM TEMP
RIGHT JOIN FULL_NAME AS F
ON TEMP.ID=F.ID;

SELECT *
FROM TEMP AS T
LEFT JOIN FULL_NAME AS F
ON T.ID=F.ID
UNION
SELECT *
FROM TEMP AS T
RIGHT JOIN FULL_NAME AS F
ON T.ID=F.ID;

SELECT *
FROM TEMP AS T
LEFT JOIN FULL_NAME AS F
ON T.ID=F.ID
WHERE F.ID IS NULL;


SELECT *
FROM TEMP AS T
RIGHT JOIN FULL_NAME AS F
ON T.ID=F.ID
WHERE T.ID IS NULL;

SELECT *
FROM TEMP AS T
LEFT JOIN FULL_NAME AS F
ON T.ID=F.ID
WHERE F.ID IS NULL
UNION
SELECT *
FROM TEMP AS T
RIGHT JOIN FULL_NAME AS F
ON T.ID=F.ID
WHERE T.ID IS NULL;


SELECT *
FROM TEMP AS A
JOIN FULL_NAME AS B
ON A.ID=B.ID;


SELECT ID FROM TEMP 
UNION 
SELECT ID FROM FULL_NAME ;

SELECT NAME FROM TEMP
UNION ALL
SELECT NAME FROM FULL_NAME;


SELECT AVG(ID)
FROM  FULL_NAME;

SELECT NAME 
FROM FULL_NAME
WHERE ID > 105;

SELECT ID,NAME
FROM FULL_NAME
WHERE ID IN(
SELECT ID FROM FULL_NAME 
WHERE ID%2=0);


SELECT MAX(ID)
FROM(SELECT * 
FROM FULL_NAME
WHERE ID >106) AS A;


CREATE VIEW V1 AS 
SELECT  NAME ,ID FROM FULL_NAME;

SELECT * FROM V1;

SELECT * FROM V1
WHERE ID< 106;

new1

SELECT * FROM FULL_NAME;
SELECT * FROM TEMP;
