CREATE DATABASE COLLEGE;
USE COLLEGE;

CREATE TABLE IIST(
ID INT ,
NAME VARCHAR(100),
AGE INT NOT NULL
);
INSERT INTO IIST VALUES( 1,"ASHVIN",20);
INSERT INTO IIST VALUES(2,"CHOUHAN",20);
SELECT * FROM  IIST;
SHOW TABLES;
CREATE TABLE STUDENT(
ROLL INT , 
NAME CHAR,
MARKS INT );
SELECT * FROM STUDENT;
INSERT INTO STUDENT
(ROLL , NAME ,MARKS)
VALUES 
(1,"A",20),
(2,"B",50);
 CREATE DATABASE XYZ;
CREATE TABLE DB(
ID INT,
NAME VARCHAR (100),
SALARY FLOAT);
INSERT INTO DB 
 (ID , NAME , SALARY)
 VALUES 
  (1 ,"ADAM", 10000 ),
  (2,"BOB",110000),
  (3,"CASEY", 40000);
  SELECT * FROM DB;