CREATE DATABASE ASHWIN;

USE ASHWIN;

CREATE TABLE DATA(
NAME VARCHAR(254) NOT NULL,
ID INT SIGNED PRIMARY KEY NOT NULL,
USER_NAME VARCHAR(254) UNIQUE NOT NULL,
USER_PASS VARCHAR(254) NOT NULL
ON DELETE CASCADE
ON UPDATE CASCADE );

SHOW DATABASES;

SHOW TABLES ;

SELECT * FROM DATA;

INSERT INTO DATA(
NAME,
ID ,
USER_NAME,
USER_PASS)
VALUES 
("ASHWIN",101,"ASH","PASSWORD"),
("KEY",102,"K","ASH"),
("CHOUHAN",103,"HAN","ENCRY");


SELECT DATA FROM ASHWIN AS A
WHERE NAME="ASHWIN";

SELECT * FROM ASHWIN LIMIT 1;

SELECT DATA FROM ASHWIN 
ORDER BY NAME DESC;


SELECT NAME ,COUNT(ID)
FROM DATA 
GROUP BY USER_NAME
HAVING USER_PASS="PASSWORD";

UPDATE DATA
SET PASSWORD="HARDING"
WHERE PASSWORD="PASSWORD";

SELECT * FROM ASHVIN AS A 
LEFT JOIN USER_PASS AS P
ON A.ID=B.ID
WHERE B.ID IS NULL;





